# Site settings
title: Jose Salavert - Senior Software Engineer
email: salavert@gmail.com
description: Personal website of Jose Salavert
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.josesalavert.com" # the base hostname & protocol for your site

# Identity
your-name: Jose Salavert
your-title: iOS Senior Software Engineer at Telefónica Digital España (Formerly Tuenti)

# Social settings
github_url: https://github.com/salavert/
linkedin_url: https://www.linkedin.com/in/jose-salavert/

# Build settings
markdown: kramdown
